--FLASHBACK，即闪回，是ORACLE10G开始推出的一个新的功能特性，目的是加快用户错误操作的恢复。
--该功能可以让被drop的对象暂时进入到RECYCLEBIN当中，相当于一个回收站。
--当用户drop某一对象后，可通过如下语句查询回收站情况：
DROP TABLE T_TEST_DROP;
SELECT A.* FROM RECYCLEBIN;
--RECYCLEBIN是一个public的同义词，本体是sys下的一个视图，名为USER_RECYCLEBIN，也就是当前用户的回收站情况。
--在SQL * PLUS还可以用如下语句查看：
>show recyclebin;
--该语句等同于
SELECT A.ORIGINAL_NAME, A.OBJECT_NAME AS RECYCLEBIN_NAME, A.TYPE AS OBJECT_TYPE, A.DROPTIME AS DROP_TIME, FROM USER_RECYCLEBIN A;
--对于FLASHBACK的删除对象仅仅是做了一个重命名的操作，此时的表应该还可以查询。
CREATE OR REPLACE TABLE T_TST_01(ID NUMBER, USERNAME VARCHAR2(20));
INSERT INTO T_TST_01(ID, USERNAME) VALUES(1, 'NULL001');
COMMIT;
DROP TABLE T_TST_01;
--通过FLASHBACK命令可以恢复回收站中的对象。
FLASHBACK TABLE T_TST_01 TO BEFORE DROP;
--想要直接删除对象不进回收站可以在最后加PURGE。
DROP TABLE T_TST_01 PURGE;
--清除回收站中指定的对象
PURGE TABLE T_TST_01;
PURGE INDEX IDX_TST_01;
--删除指定作用域中的对象，如USER_RECYCLEBIN
PURGE RECYCLEBIN;
PURGE USER_RECYCLEBIN;
PURGE DBA_RECYCLEBIN;
--清除指定表空间的对象
PURGE TABLESPACE TSNAME;
PURGE TABLESPACE TSNAME USER USERNAME;
