CREATE TABLE T_USER (
	USER_ID		BIGINT,
	USERNAME	CHAR(50),
	USER_TYPE integer, 
--	USER_VERSION	INTEGER DEFAULT 0,
	INSERT_DATE	TIMESTAMP, 
	UPDATE_TIME TIMESTAMP, 
	LAST_ACCESS_DATETIME TIMESTAMP
);

ALTER TABLE T_USER ADD CONSTRAINT PK_T_USER PRIMARY KEY (USER_ID);

--ALTER TABLE T_USER ADD (USER_TYPE integer, UPDATE_TIME TIMESTAMP);
--ALTER TABLE T_USER ADD USER_TYPE integer;
--ALTER TABLE T_USER ADD USER_VERSION integer default 0;
--ALTER TABLE T_USER ADD UPDATE_TIME TIMESTAMP;
--ALTER TABLE T_USER ADD LAST_ACCESS_DATETIME TIMESTAMP;


--INSERT INTO T_USER(USER_ID, USERNAME, INSERT_DATE) VALUES(1, '', make_timestamp(2017, 01, 01, 01, 01, 01));
--INSERT INTO T_USER(USER_ID, USERNAME, INSERT_DATE) VALUES(2, '', make_timestamp(2017, 01, 02, 22, 01, 30));
--INSERT INTO T_USER(USER_ID, USERNAME, INSERT_DATE) VALUES(3, '', '2017-10-10 12:34:56');
--INSERT INTO T_USER(USER_ID, USERNAME, INSERT_DATE) VALUES(4, '', '2017-10-11 20:00:00');
--INSERT INTO T_USER(USER_ID, USERNAME, INSERT_DATE) VALUES(5, '', now());
INSERT INTO T_USER(USER_ID, USERNAME, INSERT_DATE) VALUES(6, 'Arthur', timestamp '2017-10-20 10:00:00.1');

--POSTGRESQL新建序列参数默认值讲解 https://www.postgresql.org/docs/9.4/static/sql-createsequence.html
--使用sequence的方法 SELECT nextval('serial');
--start with不能比minvalue还小
CREATE SEQUENCE SEQ_USER_ID INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 8 CACHE 5 NO CYCLE;
